### ISSUE TITLE
AnywhereLibrary + Robot Framework: AttributeError: 'NoneType' object has no attribute 'find_elements_by_xpath'

### ISSUE THREAD

**Issue by Geruteee** [luisxiaomai/robotframework-anywherelibrary#2]
Hei everybody,

I am trying to run tests using Robot Framework RIDE + AnywhereLibrary, but I allways get an error: .FAIL AttributeError: 'NoneType' object has no attribute 'find_elements_by_xpath'

Does anybody had this problem?

**Comment by luisxiaomai** [comment]
@Geruteee  can you give other information about how you run your test? And give detailed RIDE error log.
