### ISSUE TITLE
模块导入错误

### ISSUE THREAD

**Issue by XiepengLi** [luisxiaomai/robotframework-anywherelibrary#3]
原：\Python27\lib\site-packages\AnywhereLibrary\base\waiting.py", line 3, in <module>
    from AnywhereLibrary.base import **elementfinder** as EC
修改为
\Python27\lib\site-packages\AnywhereLibrary\base\waiting.py", line 3, in <module>
    from AnywhereLibrary.base.**elementfinder** import **ElementFinder** as EC

**Comment by luisxiaomai** [comment]
没有错，elementfinder必须以模块方式全部导入，只导入ElementFinder这个类，会会缺失其他类，这类类在waiting.py里也有调用。
