### ISSUE TITLE
日志路径设置出错

### ISSUE THREAD

**Issue by XiepengLi** [luisxiaomai/robotframework-anywherelibrary#4]
报错：FAILED AnywhereLibrary Importing test library 'AnywhereLibrary' failed: **ImportError**: cannot import name GLOBAL_VARIABLES
出错处：\Python27\lib\site-packages\AnywhereLibrary\base\logging.py", line 2, in <module>
    **from robot.variables import GLOBAL_VARIABLES**
改为：

```
from robot.libraries.BuiltIn import BuiltIn
def _get_log_dir(self):
        try:
            variables = BuiltIn().get_variables()

            logfile = variables['${LOG FILE}']
            if logfile != 'NONE':
                return os.path.dirname(logfile)
            return variables['${OUTPUTDIR}']

        except RobotNotRunningError:
            return os.getcwd()
```

**Comment by luisxiaomai** [comment]
thanks, fixed by https://github.com/luisxiaomai/robotframework-anywherelibrary/commit/33594115e05b40ded434c43e3ddb0c7e40de672a
