### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'save_screenshot'

### ISSUE THREAD

**Issue by ankfeb12** [luisxiaomai/robotframework-anywherelibrary#5]
i am getting this error when trying to execute sample webviewTest.txt.  Firefox opens but quits unexpectedly. attached logs.Could you please help me. 
# $ pybot --variable platform:firefox webviewTest.txt
# webviewTest                                                                   

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: AttributeError: 'NoneType' object has no attribute 'save_screenshot'
Search "robotframework-anywherelibrary" in google                     | FAIL |
Parent suite setup failed:
## error: [Errno 61] Connection refused

[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: AttributeError: 'NoneType' object has no attribute 'save_screenshot'
webviewTest                                                           | FAIL |
Suite setup failed:
error: [Errno 61] Connection refused

Also suite teardown failed:
AttributeError: 'NoneType' object has no attribute 'quit'

1 critical test, 0 passed, 1 failed
#1 test total, 0 passed, 1 failed

**Comment by luisxiaomai** [comment]
I guess it may be the selenium installed was not matched to the firefox versin, try to update selenium using command: pip install selenium --upgrade.

You can try chrome instead and take a look at result.

**Comment by ankfeb12** [comment]
upgraded the selenium and tried with other platforms. still no success.

**Comment by luisxiaomai** [comment]
If you used proxy or if you network can connect to google. Need more information, thanks.

**Comment by ankfeb12** [comment]
upgrading the firefox fixed my problem. thanks a lot .
