### ISSUE TITLE
Robot Anywhere isn't installing on ubuntu

### ISSUE THREAD

**Issue by ricardo-oamaro** [luisxiaomai/robotframework-anywherelibrary#9]
Hello Luis, could you take a look on it? It will be very help if it works. Thank you.

pip install robotframework-anywherelibrary
Collecting robotframework-anywherelibrary
  Using cached https://files.pythonhosted.org/packages/15/d6/9e451411d3f0205510aad027f07a831e3da314ff526c739db2da23c640ed/robotframework-anywherelibrary-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x4xzkoxs/robotframework-anywherelibrary/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x4xzkoxs/robotframework-anywherelibrary/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-x4xzkoxs/robotframework-anywherelibrary/pip-egg-info
         cwd: /tmp/pip-install-x4xzkoxs/robotframework-anywherelibrary/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x4xzkoxs/robotframework-anywherelibrary/setup.py", line 8, in <module>
        execfile(join(dirname(__file__), 'src', 'AnywhereLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by luisxiaomai** [comment]
@ricardo-oamaro  please clone latest source code and run ` python3 setup.py install `
